package com.myBank.global.risk.credit.Calculations;

import java.util.Calendar;
import java.util.Locale;
import static java.util.Calendar.*;
import java.util.Date;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;

import java.time.ZoneId;

import java.math.BigInteger;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalcHelper {


  public static BigInteger diffInYears( Date startDt, Date endDt )  {
    
 
    LocalDate endld   = endDt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate startld = startDt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

    Period age = Period.between(startld, endld);

    return BigInteger.valueOf( age.getYears() );

  }
  
    public static BigInteger diffInMonths( Date startDt, Date endDt )  {
    
       System.out.println ( "stddt:"  + startDt );
       System.out.println ( "enddt:"  + endDt );
       
    LocalDate endld   = endDt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate startld = startDt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

       System.out.println ( "lstddt:"  + startld );
       System.out.println ( "lenddt:"  + endld );


    Period age = Period.between(startld, endld);


       System.out.println ( "age:"  + age );


    return BigInteger.valueOf( age.getMonths() );

  }

}